### ISSUE TITLE
support for serialization

### ISSUE THREAD

**Issue by vryy** [kylebeggs/POD-RBF#4]
It is not an issue, but a feature request. Can we have support for serialization?

**Comment by kylebeggs** [comment]
Hi @vryy , what do you mean? To not use NumPy?

**Comment by vryy** [comment]
No no, I mean to save and reuse the model without retraining.

**Comment by kylebeggs** [comment]
Added with latest release [v1.3.0](https://github.com/kylebeggs/POD-RBF/releases/tag/v1.3.0)

**Comment by vryy** [comment]
work nicely. Thanks.

**Comment by kylebeggs** [comment]
You are welcome.
